#pragma once

namespace constants {
	// Graphics
	const int SCREEN_WIDTH = 1400;
	const int SCREEN_HEIGHT = 990;

	const int CARD_IMAGE_WIDTH = 950;
	const int CARD_IMAGE_HEIGHT = 392;
	const int CARD_WIDTH = CARD_IMAGE_WIDTH / 13;
	const int CARD_HEIGHT = CARD_IMAGE_HEIGHT / 4;

	const float DRAWN_CARD_SCALE_FACTOR = 0.95f;

	const int CARD_GAP = 5;
	const int CARD_OFFSET_X = 8;
	const int CARD_OFFSET_Y = 8;

	const int HAND_OFFSET_X = 787;
	const int HAND_OFFSET_Y = 40;
	const int HAND_SPACING = 10;

	const int TOKEN_SIZE = 300;
	const float TOKEN_SCALE_FACTOR = 0.33f;

	// Gameplay
	const int DECK_SIZE = 52 * 2;
	const int HAND_SIZE = 7;
	const int NUM_PLAYERS = 2;
	const int P1 = 0;
	const int P2 = 1;

	// Cards
	const int NUM_SUITS = 4;
	const int NUM_FACES = 13;

	const int SUIT_CLUB = 13 * 0;
	const int SUIT_SPADE = 13 * 1;
	const int SUIT_HEART = 13 * 2;
	const int SUIT_DIAMOND = 13 * 3;

	const int FACE_ACE = 0;
	const int FACE_TWO = 1;
	const int FACE_THREE = 2;
	const int FACE_FOUR = 3;
	const int FACE_FIVE = 4;
	const int FACE_SIX = 5;
	const int FACE_SEVEN = 6;
	const int FACE_EIGHT = 7;
	const int FACE_NINE = 8;
	const int FACE_TEN = 9;
	const int FACE_JACK = 10;
	const int FACE_QUEEN = 11;
	const int FACE_KING = 12;

	const int WILD = 13 * 4;

	const int GAME_BOARD_SIZE = 10;
	const int GAME_BOARD[10][10] = {
	{ WILD, SUIT_DIAMOND + FACE_SIX, SUIT_DIAMOND + FACE_SEVEN, SUIT_DIAMOND + FACE_EIGHT, SUIT_DIAMOND + FACE_NINE, SUIT_DIAMOND + FACE_TEN, SUIT_DIAMOND + FACE_QUEEN, SUIT_DIAMOND + FACE_KING, SUIT_DIAMOND + FACE_ACE, WILD },
	{ SUIT_DIAMOND + FACE_FIVE, SUIT_HEART + FACE_THREE, SUIT_HEART + FACE_TWO, SUIT_SPADE + FACE_TWO, SUIT_SPADE + FACE_THREE, SUIT_SPADE + FACE_FOUR, SUIT_SPADE + FACE_FIVE, SUIT_SPADE + FACE_SIX, SUIT_SPADE + FACE_SEVEN, SUIT_CLUB + FACE_ACE },
	{ SUIT_DIAMOND + FACE_FOUR, SUIT_HEART + FACE_FOUR, SUIT_DIAMOND + FACE_KING, SUIT_DIAMOND + FACE_ACE, SUIT_CLUB + FACE_ACE, SUIT_CLUB + FACE_KING, SUIT_CLUB + FACE_QUEEN, SUIT_CLUB + FACE_TEN, SUIT_SPADE + FACE_EIGHT, SUIT_CLUB + FACE_KING },
	{ SUIT_DIAMOND + FACE_THREE, SUIT_HEART + FACE_FIVE, SUIT_DIAMOND + FACE_QUEEN, SUIT_HEART + FACE_QUEEN, SUIT_HEART + FACE_TEN, SUIT_HEART + FACE_NINE, SUIT_HEART + FACE_EIGHT, SUIT_CLUB + FACE_NINE, SUIT_SPADE + FACE_NINE, SUIT_CLUB + FACE_QUEEN },
	{ SUIT_DIAMOND + FACE_TWO, SUIT_HEART + FACE_SIX, SUIT_DIAMOND + FACE_TEN, SUIT_HEART + FACE_KING, SUIT_HEART + FACE_THREE, SUIT_HEART + FACE_TWO, SUIT_HEART + FACE_SEVEN, SUIT_CLUB + FACE_EIGHT, SUIT_SPADE + FACE_TEN, SUIT_CLUB + FACE_TEN },
	{ SUIT_SPADE + FACE_ACE, SUIT_HEART + FACE_SEVEN, SUIT_DIAMOND + FACE_NINE, SUIT_HEART + FACE_ACE, SUIT_HEART + FACE_FOUR, SUIT_HEART + FACE_FIVE, SUIT_HEART + FACE_SIX, SUIT_CLUB + FACE_SEVEN, FACE_QUEEN + SUIT_SPADE, SUIT_CLUB + FACE_NINE },
	{ SUIT_SPADE + FACE_KING, SUIT_HEART + FACE_EIGHT, SUIT_DIAMOND + FACE_EIGHT, SUIT_CLUB + FACE_TWO, SUIT_CLUB + FACE_THREE, SUIT_CLUB + FACE_FOUR, SUIT_CLUB + FACE_FIVE, SUIT_CLUB + FACE_SIX, SUIT_SPADE + FACE_KING, SUIT_CLUB + FACE_EIGHT },
	{ SUIT_SPADE + FACE_QUEEN, SUIT_HEART + FACE_NINE, SUIT_DIAMOND + FACE_SEVEN, SUIT_DIAMOND + FACE_SIX, SUIT_DIAMOND + FACE_FIVE, SUIT_DIAMOND + FACE_FOUR, SUIT_DIAMOND + FACE_THREE, SUIT_DIAMOND + FACE_TWO, SUIT_SPADE + FACE_ACE, SUIT_CLUB + FACE_SEVEN },
	{ SUIT_SPADE + FACE_TEN, SUIT_HEART + FACE_TEN, SUIT_HEART + FACE_QUEEN, SUIT_HEART + FACE_KING, SUIT_HEART + FACE_ACE, SUIT_CLUB + FACE_TWO, SUIT_CLUB + FACE_THREE, SUIT_CLUB + FACE_FOUR, SUIT_CLUB + FACE_FIVE, SUIT_CLUB + FACE_SIX },
	{ WILD, SUIT_SPADE + FACE_NINE, SUIT_SPADE + FACE_EIGHT, SUIT_SPADE + FACE_SEVEN, SUIT_SPADE + FACE_SIX, SUIT_SPADE + FACE_FIVE, SUIT_SPADE + FACE_FOUR, SUIT_SPADE + FACE_THREE, SUIT_SPADE + FACE_TWO, WILD }
	};
}